### ISSUE TITLE
Specify ToolPanel size and force widgets to be in rect.  

### ISSUE THREAD

**Issue by mishaglik** [mishaglik/Elpidifor-s-legacy#22]
- [x] Add specification in standart for widgets to fit in their rects. 
- [x] Add ```C extern "C" bool setToolBarSize(size_t w, size_h)``` that will set ToolPanel size where all widget will live ```

**Comment by mishaglik** [comment]
Widget exceeds size to specified size it will be cut

**Comment by Danti0ch** [comment]
> Widget exceeds size to specified size it will be cut

maybe the best solution for widgets that go beyond the specified size would be to add the expandability of ToolPanel at the expense of slider?

**Comment by Lord-KA** [comment]
Well, I think that slider in ToolPanel is a bad design in the majority of cases. In this project we don't support any kind of automatic layout and specify every position by hand. Thus, I feel that it should be reflected in Tool widgets too, lets require both ToolPanel dimensions and widget layout to be set by plug-in developer.

**Comment by Lord-KA** [comment]
> Add C extern "C" bool setToolBarSize(size_t w, size_h) that will set ToolPanel size where all widget will live

Don't you think that as it is Tool specific we can just pass it into `addTool()`?

**Comment by Lord-KA** [comment]
> Add specification in standart for widgets to fit in their rects.

I've just thought of it, but strictly speaking this would be either untrue or frustrating to implement in case of  `DropList`, as it has its own form (in folded state) and a form of the widgets inside (when it is open). This may be more about #23 overall, but I don't think that we should add `DropList` in spec because it is a more complicated Widget.
